### ISSUE TITLE
OperationNotSupportedException

### ISSUE THREAD

**Issue by cidudp** [bitnami/bitnami-docker-jasperreports#24]
ERROR JNDIResourceProvider,localhost-startStop-1:75 - error closing context

**Comment by juan131** [comment]
@cidudp I just launched `docker-compose up` and as you mentioned I found the following error at `/opt/bitnami/tomcat/logs/catalina.out` log file.

```
2017-02-17 08:19:38,990 ERROR JNDIResourceProvider,localhost-startStop-1:75 - error closing context
javax.naming.OperationNotSupportedException: Context is read only
	at org.apache.naming.NamingContext.checkWritable(NamingContext.java:966)
	at org.apache.naming.NamingContext.close(NamingContext.java:766)
	at com.tonbeller.tbutils.res.JNDIResourceProvider.close(JNDIResourceProvider.java:72)
	at com.tonbeller.tbutils.res.CompositeResourceProvider.close(CompositeResourceProvider.java:56)
	at com.tonbeller.tbutils.res.ResourcesFactory.initialize(ResourcesFactory.java:163)
	at com.tonbeller.tbutils.res.ResourcesFactory.<init>(ResourcesFactory.java:92)
	at com.tonbeller.tbutils.res.ResourcesFactory.<clinit>(ResourcesFactory.java:89)
	at com.tonbeller.tbutils.res.ResourcesFactoryContextListener.contextInitialized(ResourcesFactoryContextListener.java:23)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4853)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5314)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:753)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:729)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1092)
	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1834)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
Apparently it seems an issue on an Apache Library.

**Comment by sameersbn** [comment]
@juan http://community.jaspersoft.com/questions/822153/error-closing-context suggests the creation of `WEB-INF/classes/resfactory.properties` consisting of the line `tbeller.usejndi=false`.

For test purposes I applied the changes using the following patch and found that the message went away. I an not sure if we should be making this fix in the jasperreports module though.

```diff
diff --git a/6/rootfs/app-entrypoint.sh b/6/rootfs/app-entrypoint.sh
index 330739e..e51a26f 100755
--- a/6/rootfs/app-entrypoint.sh
+++ b/6/rootfs/app-entrypoint.sh
@@ -7,6 +7,7 @@ check_for_updates &
 
 if [[ "$1" == "nami" && "$2" == "start" ]] || [[ "$1" == "/init.sh" ]]; then
   nami_initialize jasperreports
+  echo tbeller.usejndi=false > /opt/bitnami/jasperreports/WEB-INF/classes/resfactory.properties
   info "Starting jasperreports..."
 fi
```

**Comment by Rameshwarnathyadav** [comment]
please suggest for me this issue ..  on the live server in jasper report server

**Comment by Rameshwarnathyadav** [comment]
> @cidudp I just launched `docker-compose up` and as you mentioned I found the following error at `/opt/bitnami/tomcat/logs/catalina.out` log file.
> 
> ```
> 2017-02-17 08:19:38,990 ERROR JNDIResourceProvider,localhost-startStop-1:75 - error closing context
> javax.naming.OperationNotSupportedException: Context is read only
> 	at org.apache.naming.NamingContext.checkWritable(NamingContext.java:966)
> 	at org.apache.naming.NamingContext.close(NamingContext.java:766)
> 	at com.tonbeller.tbutils.res.JNDIResourceProvider.close(JNDIResourceProvider.java:72)
> 	at com.tonbeller.tbutils.res.CompositeResourceProvider.close(CompositeResourceProvider.java:56)
> 	at com.tonbeller.tbutils.res.ResourcesFactory.initialize(ResourcesFactory.java:163)
> 	at com.tonbeller.tbutils.res.ResourcesFactory.<init>(ResourcesFactory.java:92)
> 	at com.tonbeller.tbutils.res.ResourcesFactory.<clinit>(ResourcesFactory.java:89)
> 	at com.tonbeller.tbutils.res.ResourcesFactoryContextListener.contextInitialized(ResourcesFactoryContextListener.java:23)
> 	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4853)
> 	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5314)
> 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
> 	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:753)
> 	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:729)
> 	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
> 	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1092)
> 	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1834)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 	at java.lang.Thread.run(Thread.java:745)
> ```
> 
> Apparently it seems an issue on an Apache Library.

whats type of issues in jasper report ..

**Comment by marcosbc** [comment]
Hi @Rameshwarnathyadav, please check this reply: https://github.com/bitnami/bitnami-docker-jasperreports/issues/24#issuecomment-297696827

If you continue finding issues, please open a new Issue and link to this one, since it's already quite old.
