### ISSUE TITLE
Additional email configuration request

### ISSUE THREAD

**Issue by mrloud** [bitnami/bitnami-docker-jasperreports#49]
Thank you for the great image, but I would like to make a request.

Concerning email configuration there is no way to set mail.smtp.auth and mail.smtp.starttls.enable in applicationContext-report-scheduling.xml to true.  Our mail servers require this to send mail -

>         <property name="javaMailProperties">
>             <props>
>                 <prop key="mail.smtp.sendpartial">true</prop>
>                 <prop key="mail.smtp.auth">true</prop>
>                 <prop key="mail.smtp.starttls.enable">true</prop>
>             </props>
>         </property>

The default I believe is this -

>         <property name="javaMailProperties">
>             <props>
>                 <prop key="mail.smtp.sendpartial">true</prop>
>                 <prop key="mail.smtp.auth">false</prop>
>             </props>
>         </property>

Is this something you would consider adding?

**Comment by andresbono** [comment]
Hi @mrloud,

Did you try configuring SMTP with the environment variables that are specified in the [README.md](https://github.com/bitnami/bitnami-docker-jasperreports#smtp-configuration)? Aren't those variables enough to make it work for you?

Could you please let us know how are you checking that smtp is correctly configured in your scenario?

Thanks!
-Andrés B.

**Comment by mrloud** [comment]
I'm testing it by scheduling a run and having it execute immediately.

Clipped environment settings from container inspect:

>                 "SMTP_HOST=smtp.office365.com",
>                 "SMTP_PORT=587",
>                 "SMTP_EMAIL=XXXX",
>                 "SMTP_USER=XXXX",
>                 "SMTP_PASSWORD=XXXX",
>                 "SMTP_PROTOCOL=smtp",

Stacktrace from container logs:

> 2018-04-16 13:50:32,178 ERROR ReportExecutionJob,quartzScheduler_Worker-1:366 - The job error notification was not completed. An error occurred while sending it. (Error UID: 41463466-d8d8-4193-a91e-5b25ec269bd1)
org.springframework.mail.MailSendException: Failed messages: com.sun.mail.smtp.SMTPSendFailedException: 530 5.7.57 SMTP; Client was not authenticated to send anonymous mail during MAIL FROM [SN4PR0601CA0017.namprd06.prod.outlook.com];
message exception details (1) are:
Failed message 1:
com.sun.mail.smtp.SMTPSendFailedException: 530 5.7.57 SMTP; Client was not authenticated to send anonymous mail during MAIL FROM [SN4PR0601CA0017.namprd06.prod.outlook.com]
                                                                                                                                           
        at com.sun.mail.smtp.SMTPTransport.issueSendCommand(SMTPTransport.java:1388)                                                       
        at com.sun.mail.smtp.SMTPTransport.mailFrom(SMTPTransport.java:959)                                                                
        at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:583)                                                             
        at org.springframework.mail.javamail.JavaMailSenderImpl.doSend(JavaMailSenderImpl.java:416)                                        
        at org.springframework.mail.javamail.JavaMailSenderImpl.send(JavaMailSenderImpl.java:340)                                          
        at org.springframework.mail.javamail.JavaMailSenderImpl.send(JavaMailSenderImpl.java:336)                                          
        at com.jaspersoft.jasperserver.api.engine.scheduling.quartz.ReportExecutionJobMailNotificationImpl.sendMailNotification(ReportExecutionJobMailNotificationImpl.java:140)                                                                                                      
        at com.jaspersoft.jasperserver.api.engine.scheduling.quartz.ReportExecutionJob.sendMailNotification(ReportExecutionJob.java:1123)  
        at com.jaspersoft.jasperserver.api.engine.scheduling.quartz.ReportExecutionJob.executeAndSendReport(ReportExecutionJob.java:581)   
        at com.jaspersoft.jasperserver.api.engine.scheduling.quartz.ReportExecutionJob.execute(ReportExecutionJob.java:248)                
        at org.quartz.core.JobRunShell.run(JobRunShell.java:213)                                                                           
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557)

**Comment by andresbono** [comment]
Thanks for the information, we can reproduce the issue.

We will investigate a valid solution for this and we will update the container.

Thanks again for the valuable feedback,

-Andrés B.

**Comment by mrloud** [comment]
Just tried 6.4.3-r14 and see the same issue.

**Comment by mrloud** [comment]
Ah, ok, thanks.  I wasn't sure if I missed something so gave it another try :)

**Comment by miguelaeh** [comment]
Hi @mrloud,
We have solved this issue and released an update version. Now, we support by default the authentication with the SMTP server, but for security reasons, now we do not support the use of SMTP servers that do not provide authentication, in any case you can change that changing the `WEB-INF/applicationContext-report-scheduling.xml` file.
Thanks for your issue.

**Comment by sarawutsangaroon** [comment]
> Hi @mrloud,
> We have solved this issue and released an update version. Now, we support by default the authentication with the SMTP server, but for security reasons, now we do not support the use of SMTP servers that do not provide authentication, in any case you can change that changing the `WEB-INF/applicationContext-report-scheduling.xml` file.
> Thanks for your issue.

Can you share what version can solve this issue ?

**Comment by andresbono** [comment]
Hi @sarawutsangaroon, we recommend you to use the latest version of the image. Are you facing some issues with the latest one?
