### ISSUE TITLE
LDAP Authentication 

### ISSUE THREAD

**Issue by SudharsanN** [bitnami/bitnami-docker-jasperreports#70]
We are trying to set up LDAP authentication for JasperReports by following the steps mentioned at https://community.jaspersoft.com/documentation/tibco-jasperreports-server-authentication-cookbook/v720/ldap-authentication .

I manually edited the sample-applicationContext-externalAuth-LDAP.xml and renamed it as applicationContext-externalAuth-LDAP.xml and placed it at "/opt/bitnami/jasperreports/WEB-INF" of the running container and restarted the container. I have attached the file along with this ticket.

On restart of the container below is the error message I am seeing during start up. In spite of this error, the container starts and when I try to access the site, I get a 404 error page.

Error creating bean with name 'proxyBasicProcessingFilter' defined in ServletContext resource [/WEB-INF/applicationContext-externalAuth-LDAP.xml]: Error setting property values; nested exception is org.springframework.beans.NotWritablePropertyException: Invalid property 'authenticationManager' of bean class [com.jaspersoft.jasperserver.api.security.externalAuth.ExternalAuthBasicProcessingFilter]: Bean property 'authenticationManager' is not writable or has an invalid setter method. Does the parameter type of the setter match the return type of the getter?
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1571)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1281)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:551)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:481)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:312)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:308)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543)
        at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:443)
        at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:325)
        at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:107)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4685)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5146)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:717)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:690)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:705)
        at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1133)
        at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1867)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
        at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
        at org.apache.catalina.startup.HostConfig.deployDirectories(HostConfig.java:1045)
        at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:429)
        at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1576)
        at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:309)
        at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
        at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:423)
        at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:366)
        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:936)
        at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:841)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1384)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1374)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
        at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134)
        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:909)
        at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:262)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.StandardService.startInternal(StandardService.java:421)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:932)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.startup.Catalina.start(Catalina.java:633)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:344)
        at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:475)
Caused by: org.springframework.beans.NotWritablePropertyException: Invalid property 'authenticationManager' of bean class [com.jaspersoft.jasperserver.api.security.externalAuth.ExternalAuthBasicProcessingFilter]: Bean property 'authenticationManager' is not writable or has an invalid setter method. Does the parameter type of the setter match the return type of the getter?
        at org.springframework.beans.BeanWrapperImpl.createNotWritablePropertyException(BeanWrapperImpl.java:239)
        at org.springframework.beans.AbstractNestablePropertyAccessor.processLocalProperty(AbstractNestablePropertyAccessor.java:435)
        at org.springframework.beans.AbstractNestablePropertyAccessor.setPropertyValue(AbstractNestablePropertyAccessor.java:290)
        at org.springframework.beans.AbstractNestablePropertyAccessor.setPropertyValue(AbstractNestablePropertyAccessor.java:278)
        at org.springframework.beans.AbstractPropertyAccessor.setPropertyValues(AbstractPropertyAccessor.java:95)
        at org.springframework.beans.AbstractPropertyAccessor.setPropertyValues(AbstractPropertyAccessor.java:75)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1567)

Can someone look into this and let me know what I am doing wrong.
[applicationContext-externalAuth-LDAP.txt](https://github.com/bitnami/bitnami-docker-jasperreports/files/3746438/applicationContext-externalAuth-LDAP.txt)

**Comment by javsalgar** [comment]
Hi,

We've been working with LDAP authentication with some of our solutions. We will take a look and try to reproduce it in our side. @rafariossaa you have more experience with LDAP, could you take a look?

**Comment by rafariossaa** [comment]
Hi @SudharsanN ,
  Sorry for the long delay, I am taking a look into this.

**Comment by rafariossaa** [comment]
Hi @SudharsanN,
  This seems to be a know issue in jasperreports.
  Could you take a look to this thread? https://community.jaspersoft.com/questions/1138586/jasperreports-ldap-setting-issue-after-upgrade-71-72 .

**Comment by rafariossaa** [comment]
Hi @SudharsanN ,
  Any news ?

**Comment by Jonbj** [comment]
Hi all,
can I reoen the issue?
I found some variable on /jasperreports/jasperreports/buildomatic/default_master.properties file, and i tired to configure to use LDAP over Active Directory:

external.ldapUrl=ldap://dcip:389/DC=domain,DC=local
external.ldapDn=CN=username,OU=ou,DC=domain,DC=local
external.ldapPassword=secret

but nothing semms change on the login side.
Can I use this variable or I need to manually change applicationContext-externalAuth-LDAP.xml inside the container?

**Comment by rafariossaa** [comment]
Hi,
  I am not very sure myself. I think this question would be better answered in jasperreports forums.
  In other applications you need also to set other parameters that indicate the authentication method used.

**Comment by Jonbj** [comment]
According with this document, I have to insert the file applicationContext-externalAuth-LDAP.xml in the WEB-INF directory and insert variable in the default_master.properties file.

https://docs.tibco.com/pub/js-jrs/7.1.1/doc/pdf/JasperReportsServer-Auth-Cookbook.pdf?id=7

**Comment by rafariossaa** [comment]
Hi,
 Thanks for providing that information.
 As I can see in the sections 3.4.1 and 3.4.2 of that document, there are two options, or setting it in `default_master.properties` before installation, or by creating the bean indicated in 3.4.2.
  I think that as you have already installed jasperreport the `default_master.properties` files is not used again and the bean is not created automatically.

**Comment by rafariossaa** [comment]
Hi, 
  Any news on this ?

**Comment by rafariossaa** [comment]
I am closing this issue.
Please, feel free to reopen it or to open a new one if needed.
