### ISSUE TITLE
Send email via Gmail - Start tls

### ISSUE THREAD

**Issue by dondragon2** [bitnami/bitnami-docker-jasperreports#81]
**Description**

I am using `docker.io/bitnami/jasperreports:latest` in kubernetes installation but for i am not able to send emails via Gmail which requires start_tls to be set on the stmp configurations

**Describe the results you received:**

```2020-09-09T19:03:31,587 ERROR SecureExceptionHandlerImpl,quartzScheduler_Worker-1:116 - There was an error on the server. Try again or contact site administrators. (Error UID: d223bc01-886e-4fa3-bc6c-a41fe6188d6b)
2020-09-09T19:03:31,587 ERROR ReportExecutionJob,quartzScheduler_Worker-1:367 - The job error notification was not completed. An error occurred while sending it. (Error UID: d223bc01-886e-4fa3-bc6c-a41fe6188d6b) org.springframework.mail.MailSendException: Failed messages: com.sun.mail.smtp.SMTPSendFailedException: 530 5.7.0 Must issue a STARTTLS command first. v202sm3546010qka.5 - gsmtp
; message exception details (1) are:
Failed message 1:
com.sun.mail.smtp.SMTPSendFailedException: 530 5.7.0 Must issue a STARTTLS command first. v202sm3546010qka.5 - gsmtp
	at com.sun.mail.smtp.SMTPTransport.issueSendCommand(SMTPTransport.java:2114)
	at com.sun.mail.smtp.SMTPTransport.mailFrom(SMTPTransport.java:1618)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1119)
	at org.springframework.mail.javamail.JavaMailSenderImpl.doSend(JavaMailSenderImpl.java:450)
	at org.springframework.mail.javamail.JavaMailSenderImpl.send(JavaMailSenderImpl.java:346)
	at org.springframework.mail.javamail.JavaMailSenderImpl.send(JavaMailSenderImpl.java:341)
	at com.jaspersoft.jasperserver.api.engine.scheduling.quartz.ReportExecutionJobMailNotificationImpl.sendMailNotification(ReportExecutionJobMailNotificationImpl.java:141)
	at com.jaspersoft.jasperserver.api.engine.scheduling.quartz.ReportExecutionJob.sendMailNotification(ReportExecutionJob.java:1124)
	at com.jaspersoft.jasperserver.api.engine.scheduling.quartz.ReportExecutionJob.executeAndSendReport(ReportExecutionJob.java:582)
	at com.jaspersoft.jasperserver.api.engine.scheduling.quartz.ReportExecutionJob.execute(ReportExecutionJob.java:249)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
2020-09-09T19:03:31,670 ERROR SecureExceptionHandlerImpl,quartzScheduler_Worker-1:116 - There was an error on the server. Try again or contact site administrators. (Error UID: 4977da78-cabd-4621-bc0c-1097017ffeca)
2020-09-09T19:03:31,670 ERROR ReportExecutionJob,quartzScheduler_Worker-1:367 - fail to send out alert mail notification (Error UID: 4977da78-cabd-4621-bc0c-1097017ffeca) org.springframework.mail.MailSendException: Failed messages: com.sun.mail.smtp.SMTPSendFailedException: 530 5.7.0 Must issue a STARTTLS command first. 7sm3561898qkc.73 - gsmtp
; message exception details (1) are:
Failed message 1:
com.sun.mail.smtp.SMTPSendFailedException: 530 5.7.0 Must issue a STARTTLS command first. 7sm3561898qkc.73 - gsmtp
	at com.sun.mail.smtp.SMTPTransport.issueSendCommand(SMTPTransport.java:2114)
	at com.sun.mail.smtp.SMTPTransport.mailFrom(SMTPTransport.java:1618)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1119)
	at org.springframework.mail.javamail.JavaMailSenderImpl.doSend(JavaMailSenderImpl.java:450)
	at org.springframework.mail.javamail.JavaMailSenderImpl.send(JavaMailSenderImpl.java:346)
	at org.springframework.mail.javamail.JavaMailSenderImpl.send(JavaMailSenderImpl.java:341)
	at com.jaspersoft.jasperserver.api.engine.scheduling.quartz.ReportExecutionJobAlertImpl.sendAlertMail(ReportExecutionJobAlertImpl.java:97)
	at com.jaspersoft.jasperserver.api.engine.scheduling.quartz.ReportExecutionJob.sendAlertMail(ReportExecutionJob.java:768)
	at com.jaspersoft.jasperserver.api.engine.scheduling.quartz.ReportExecutionJob.executeAndSendReport(ReportExecutionJob.java:607)
	at com.jaspersoft.jasperserver.api.engine.scheduling.quartz.ReportExecutionJob.execute(ReportExecutionJob.java:249)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
```

**Describe the results you expected:**

Emails to be sent

**Comment by juan131** [comment]
Hi @dondragon2 

This image uses a set of environment variables (`SMTP_XXX`) to configure SMTP, see:

- https://github.com/bitnami/bitnami-docker-jasperreports#smtp-configuration

If you'e using the [Bitnami Jasperreports ](https://github.com/bitnami/charts/tree/master/bitnami/jasperreports) to install it in Kubernetes, the chart offers you a set of parameters (`smtpXXX`) that are mapped to these environment variables, see:

- https://github.com/bitnami/charts/tree/master/bitnami/jasperreports#parameters

Could you please give them a try to customize your SMTP settings? If you are still running into issues, please share the exact parameters you're using (or values.yaml) you'e using to deploy the chart.

**Comment by dondragon2** [comment]
Hi @juan131 

Below are the environment variables that I am using.

```
SMTP_USER=test@test.com
SMTP_PROTOCOL=smtp
SMTP_PORT=587
SMTP_HOST=smtp.gmail.com
SMTP_EMAIL=test@test.com
SMTP_PASSWORD=Test1234
```

but from the configuration I don't see where to set the STARTTLS parameter. I think this is not exposed.
Also, may be this is unrelated but I am seeing the following error as well.

```
2020-09-10T15:00:00,155 ERROR ErrorLogger,JasperServerMaintenanceScheduler_Worker-1:2407 - Job (DEFAULT.accessEventPurgerJob threw an exception. org.quartz.SchedulerException: Job threw an unhandled exception. [See nested exception: com.jaspersoft.jasperserver.api.engine.scheduling.quartz.JSJobMethodInvocationFailedException: Invocation of method 'purgeAccessEvents' on target class [class com.sun.proxy.$Proxy75] failed; nested exception is org.springframework.dao.DataAccessResourceFailureException: could not execute statement; nested exception is org.hibernate.exception.JDBCConnectionException: could not execute statement]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: com.jaspersoft.jasperserver.api.engine.scheduling.quartz.JSJobMethodInvocationFailedException: Invocation of method 'purgeAccessEvents' on target class [class com.sun.proxy.$Proxy75] failed; nested exception is org.springframework.dao.DataAccessResourceFailureException: could not execute statement; nested exception is org.hibernate.exception.JDBCConnectionException: could not execute statement
	at com.jaspersoft.jasperserver.api.engine.scheduling.quartz.JSMethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(JSMethodInvokingJobDetailFactoryBean.java:254)
	at com.jaspersoft.jasperserver.api.engine.scheduling.quartz.JSQuartzJobBean.execute(JSQuartzJobBean.java:51)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	... 1 more
Caused by: org.springframework.dao.DataAccessResourceFailureException: could not execute statement; nested exception is org.hibernate.exception.JDBCConnectionException: could not execute statement
	at org.springframework.orm.hibernate5.SessionFactoryUtils.convertHibernateAccessException(SessionFactoryUtils.java:220)
	at org.springframework.orm.hibernate5.HibernateTemplate.doExecute(HibernateTemplate.java:364)
	at org.springframework.orm.hibernate5.HibernateTemplate.executeWithNativeSession(HibernateTemplate.java:328)
	at org.springframework.orm.hibernate5.HibernateTemplate.bulkUpdate(HibernateTemplate.java:1133)
	at com.jaspersoft.jasperserver.api.logging.access.service.impl.AccessServiceImpl.purgeAccessEvents(AccessServiceImpl.java:186)
	at sun.reflect.GeneratedMethodAccessor758.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:282)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
	at com.sun.proxy.$Proxy75.purgeAccessEvents(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor757.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:265)
	at com.jaspersoft.jasperserver.api.engine.scheduling.quartz.JSMethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(JSMethodInvokingJobDetailFactoryBean.java:247)
	... 3 more
Caused by: org.hibernate.exception.JDBCConnectionException: could not execute statement
	at org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java:48)
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:42)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:111)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:97)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:178)
	at org.hibernate.hql.internal.ast.exec.BasicExecutor.doExecute(BasicExecutor.java:100)
	at org.hibernate.hql.internal.ast.exec.BasicExecutor.execute(BasicExecutor.java:59)
	at org.hibernate.hql.internal.ast.exec.DeleteExecutor.execute(DeleteExecutor.java:110)
	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.executeUpdate(QueryTranslatorImpl.java:442)
	at org.hibernate.engine.query.spi.HQLQueryPlan.performExecuteUpdate(HQLQueryPlan.java:374)
	at org.hibernate.internal.SessionImpl.executeUpdate(SessionImpl.java:1512)
	at org.hibernate.query.internal.AbstractProducedQuery.doExecuteUpdate(AbstractProducedQuery.java:1526)
	at org.hibernate.query.internal.AbstractProducedQuery.executeUpdate(AbstractProducedQuery.java:1504)
	at org.springframework.orm.hibernate5.HibernateTemplate$38.doInHibernate(HibernateTemplate.java:1145)
	at org.springframework.orm.hibernate5.HibernateTemplate$38.doInHibernate(HibernateTemplate.java:1133)
	at org.springframework.orm.hibernate5.HibernateTemplate.doExecute(HibernateTemplate.java:361)
	... 23 more
Caused by: java.sql.SQLTransientConnectionException: (conn=1181451) You can't specify target table 'JIAccessEvent' for update in FROM clause
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:79)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:153)
	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:274)
	at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:229)
	at org.mariadb.jdbc.ClientSidePreparedStatement.execute(ClientSidePreparedStatement.java:149)
	at org.mariadb.jdbc.ClientSidePreparedStatement.executeUpdate(ClientSidePreparedStatement.java:181)
	at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105)
	at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:175)
	... 34 more
Caused by: org.mariadb.jdbc.internal.util.exceptions.MariaDbSqlException: You can't specify target table 'JIAccessEvent' for update in FROM clause
	at org.mariadb.jdbc.internal.util.exceptions.MariaDbSqlException.of(MariaDbSqlException.java:34)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.exceptionWithQuery(AbstractQueryProtocol.java:194)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.exceptionWithQuery(AbstractQueryProtocol.java:177)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:321)
	at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:220)
	... 39 more
Caused by: java.sql.SQLException: You can't specify target table 'JIAccessEvent' for update in FROM clause
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readErrorPacket(AbstractQueryProtocol.java:1688)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readPacket(AbstractQueryProtocol.java:1550)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:1513)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:318)
	... 40 more
```

**Comment by juan131** [comment]
Hi @dondragon2 

> but from the configuration I don't see where to set the STARTTLS parameter. I think this is not exposed.

That's done by default. Here you have the function used in the init logic to configure that specific option:

```javascript
$app.helpers.configureTLSForSMTP = function() {
  // Set the authentication to true, we do not support use SMTP servers without authentication.
  $file.substitute(
    'WEB-INF/applicationContext-report-scheduling.xml',
    /<prop key="mail\.smtp\.auth">false<\/prop>/,
    '<prop key="mail.smtp.auth">true</prop>\n\t\t<prop key="mail.smtp.starttls.enable">true</prop>',
    {abortOnUnmatch: true}
  );
};
```

Could you please double-check the `applicationContext-report-scheduling.xml` content?

Regarding the log error you shared, it seems some issue with the MariaDB database. Could you please share the whole manifests you're using to deploy Jasperreports so I can take a look and try to reproduce the issue on my side?
